trained 5 new models and integrated them into the repo
EngreitzLab/ENCODE_rE2G pull request #40
Opened 2024-05-07 19:42 UTC by atancoder

## Test Plan

Dry-run snakemake, and verified that the correct model was chosen: https://pastebin.com/GxmSKtKT.

2024-05-08 21:34 UTC, mayasheth commented on models/atac_h3k27ac_intact_hic/feature_table.tsv
on this model and others with H3K27ac, you may want to first try a feature table with, e.g., the following input_cols, then select a final feature set based on feature analysis:
- normalized_atac_prom
- normalized_atac_enh
- normalized_h3k27ac_prom
- normalized_h3k27ac_enh
- activity_base
- TargetGenePromoterActivityQuantile

2024-05-08 21:34 UTC, mayasheth commented on models/atac_h3k27ac_megamap/feature_table.tsv
same comment as above re: other ATAC and H3K27ac features

2024-05-08 21:36 UTC, mayasheth commented on models/dhs_h3k27ac_intact_hic/feature_table.tsv
Here, you should test the following and select final feature set:
normalized_dhs_prom
normalized_dhs_enh
normalized_h3k27ac_prom
normalized_h3k27ac_enh
activity_base
TargetGenePromoterActivityQuantile

2024-05-08 21:36 UTC, mayasheth commented on models/dhs_h3k27ac_megamap/feature_table.tsv
see comment on DHS/H3K27ac/Intact Hi-C model

2024-05-08 21:38 UTC, mayasheth requested changes
Nice work, maybe just test some additional features in the H3k27ac models before finalizing? Can you also paste the image of the PR curves/AUPRC by distance to TSS barplots from CRISPR comparison pipeline, as I'm not able to view the html attachment.

2024-05-22 22:39 UTC, atancoder commented
> Nice work, maybe just test some additional features in the H3k27ac models before finalizing? Can you also paste the image of the PR curves/AUPRC by distance to TSS barplots from CRISPR comparison pipeline, as I'm not able to view the html attachment.

Download the html and then open it to view it properly

2024-05-22 22:47 UTC, atancoder commented on models/atac_intact_hic/feature_table.tsv
> +normalizedATAC_prom	normalized_atac_prom		mean	0	ATAC signal at P
Perhaps we should change this as well since we know ATAC at promoter isn't a good feature, at least for the encode datasets?

2024-05-22 23:12 UTC, mayasheth commented
Hmm I chose these based on the all feature set analysis so it should be okay. On May 22, 2024, at 15:48, Anthony Tan ***@***.***> wrote:﻿
@atancoder commented on this pull request.



In models/atac_intact_hic/feature_table.tsv:
> @@ -0,0 +1,9 @@
+feature	input_col	second_input	aggregate_function	fill_value	nice_name
+numTSSEnhGene	numTSSEnhGene		max	0	# TSSs between E and P
+distanceToTSS	distance		min		Distance to TSS
+normalizedATAC_prom	normalized_atac_prom		mean	0	ATAC signal at P

Perhaps we should change this as well since we know ATAC at promoter isn't a good feature, at least for the encode datasets?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2024-05-29 19:58 UTC, atancoder commented
@mayasheth does this PR look good to you?

2024-05-29 21:10 UTC, mayasheth commented on resources/feature_tables/final_feature_set_ATAC_h3k27ac_hic.tsv
edit "H3K2ac signal at P" to "H3K27ac signal at P"

2024-05-29 21:11 UTC, mayasheth commented on resources/feature_tables/final_feature_set_ATAC_h3k27ac_hic.tsv
Otherwise looks good to me!

2024-05-29 21:12 UTC, mayasheth approved these changes

2024-05-29 23:19 UTC, merged